### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by sidevesh** [swinzy/auto-brightness-toggle#2]
This currently does not support gnome 44 and I tried to make it work by adding gnome44 to supported versions manually, the quick toggle then loads but shows up broken with no text inside the button.

**Comment by jackal-kr** [comment]
In Gnome 44 they changed the property name of the button from label to title so that in order to make this extension compatible with the Gnome 44 do the following

1) Go to extension folder
    `cd ~/.local/share/gnome-shell/extensions/auto-brightness-toggle@sao.studio/`
2) Open **metadata.json**, change the line with the compatible version, and save it. 
   from `"shell-version": ["43"], `
   to     `"shell-version": ["43","44"],` 
3) Then open **extension.js**, make the below changes, and save it.
   3.1) beginning of the file add the below two lines
      `const Config = imports.misc.config;`
      `const ShellVersion = Number(Config.PACKAGE_VERSION.split('.')[0]);`
   3.2) make the following change in the  **_init()** function of the **class AutoBrightnessToggl**e  
   from `label: "Auto Brightness",`
   to     `[ShellVersion >= 44 ? 'title' : 'label']: "Auto Brightness",`
4) Now it is compatible with both versions 43 and 44 -> re-login and all will work :)

P.S.
   The code taken from the Caffeine extension and just a bit adapted to this one... :)

**Comment by sidevesh** [comment]
@jackal-kr that worked for me too, thanks! Can you raise it as a PR and @m1nicrusher can we get this implemented ?
